### PR TITLE
REST API module added

### PR DESCRIPTION
**Pull request by djavolak**
Hi,
I've made a simple module that extends cms with an API, implementing just page entity for now. If you like this as a base, it can be implemented for all entities. It includes simple filters which works with entities, and can display only the required data in custom format.

### CODE REVIEW

**Comment by oleksandr-torosh** [comment]
Great job! Merged.
I will add small changes to support multi-language routes

**Comment by djavolak** [comment]
Thx :)
Glad you like it. I overlooked that routes are using I8N.

I've also created a Vagrant box for this project, but I had to use phalcon version 2.* in composer, in order to set up the cms. But I've got strange error that said it requires v2.1.7 or greater, even though that version is installed (2.1.8 if I am not mistaken is the last on 2.1.* branch).

Did not get to test out all features on this box, but I can post Vagrantfile & upload the box, and we can test it until confirmed that works, so it can be used.

**Comment by oleksandr-torosh** [comment]
@djavolak I started work on Docker container instead of Vagrant. You can check https://github.com/oleksandr-torosh/yona-cms/tree/docker

**Comment by djavolak** [comment]
ah, nice, I actually like it more, but I just started working with it, so it was easier to setup vagrant for this PR :)

**Pull request merged**
